### ISSUE TITLE
how to add custom field for page setting

### ISSUE THREAD

**Issue by faizananwerali** [witsec/mobirise-page-name#1]
In Line 10 in app.js

    a.$body.find("#app-page-settings .app-layer-cont").append('<div class="form-group"><label for="page_header_custom">Inside &lt;head&gt; code:</label><textarea id="page_header_custom" class="form-control" data-page-settings="header_custom" rows="5" placeholder="Paste any valid HTML code here. The code will be inserted to the end of &lt;head&gt section, right before &lt;/head&gt"></textarea></div><div class="form-group"><label for="page_footer_custom">End of &lt;body&gt; code:</label><textarea id="page_footer_custom" class="form-control" data-page-settings="footer_custom" rows="5" placeholder="Paste any valid HTML code here. The code will be inserted to the end of <body> section, right before &lt;/body&gt; tag"></textarea></div><div class="form-group"><label for="page_before_html">Before &lt;!DOCTYPE&gt;, &lt;html&gt; and &lt;head&gt; tags:</label><textarea id="page_before_html" class="form-control" data-page-settings="html_before" rows="5" placeholder="Paste the code you want to have in the VERY FIRST LINE of your page, before &lt;!DOCTYPE&gt;, <html> and <head> tags. Use for server side scripts (PHP, ASP, etc)"></textarea></div>');

You have added three field. My questions are:
1.) How does data-page-settings is working?
2.) How to add another custom field? and have action on 'publishHTML' trigger?

My problem: when you publish site it doesn't add facebook sharing code.

Sample: 

      	
	
	<meta name="twitter:description" content="More than 25 years of professional services, Transport Service are operating with 50 contractual vehicles all over Pakistan and tours and event management services at 100 destination all over globe.">
	<meta name="twitter:image" content="assets/images/banner.webp">
	<meta name="twitter:image:alt" content="Transport Service">
	
	
	
	
	
	<meta property="og:site_name" content="Transport Service">
	<meta property="og:title" content="Transport ServiceN">
	<meta property="og:description" content="More than 25 years of professional services, Transport Service are operating with 50 contractual vehicles all over Pakistan and tours and event management services at 100 destination all over globe.">
	<meta property="og:type" content="website">
	<meta property="og:url" content="https://mydomain.com">
	
	<meta property="og:image:type" content="image/webp">
	<meta property="og:image:alt" content="Transport Service">
	
	
	
	<meta itemprop="name" content="ransport Service">
	<meta itemprop="description" content="More than 25 years of professional services, Transport Service are operating with 50 contractual vehicles all over Pakistan and tours and event management services at 100 destination all over globe.">
	<meta itemprop="image" content="assets/images/banner.webp">
	 

I'm writing an extension which will automatically add this on every page when publish but the problem is there is no documentation and I also can't access developer tools. I need your help developing this extension.

**Comment by witsec** [comment]
These fields are supported by Mobirise by default, which made implementation a lot easier. If you want to add custom fields, Mobirise doesn't save it without additional coding.

Are you making an extension with which you can add these fields for every page or for the entire project?
What exactly doesn't work right now?

**Comment by faizananwerali** [comment]
Custom field for every page. I don't know how to do that. Also how do you
debug it? I can't even access developer tools. Can you make a simple demo
video on how to make a mobirise extension. I have so many ideas but I don't
know where to start.

**Comment by witsec** [comment]
Mobirise doesn't feature developer tools or a console or anything unfortunately. It's basically trial and error, although I do make use of "alert" a lot ;).

There isn't a lot of documentation available, but there's this:
- https://mobirise.com/docs
- https://witsec.nl/mobirise/wiki

Other than that, all my code is on GitHub, so if you see something you like, just check out the code. Feel free to ask if something isn't clear.

**Comment by faizananwerali** [comment]
Oh great. Thanks for letting me know. Also just to quickly get started how
to custom field for every page and save it and use it when publishing it?
Also how do you about the details that you mentioned in your wiki?

**Comment by witsec** [comment]
Adding a new field is easy, just check out the code that's there already. But making sure the info is saved and that the field gets updated when you switch pages is another thing.

It may be easier adding a button that says "Custom Code" (or whatever you like), which opens up a dialog window, on which you add all the fields required: textarea + update button, most likely.

Then when you click that "update" button, it should save the text inside the "textarea" to the project file.

I do most of these things in my extensions too, altough I haven't yet made a per-page setting before, but I reckon what I describe above is the easiest way. Might not be so easy on your first attempt, but that also depends on your knowledge/experience and all.
